// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Warframe_Market_Manager.Lib.WFM.QuickType;
//
//    var allItems = AllItems.FromJson(jsonString);

namespace Warframe_Market_Manager.Lib.WFM.QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public class AllItems_QuickType
    {
        [JsonProperty("payload", NullValueHandling = NullValueHandling.Ignore)]
        public Payload Payload { get; set; }

        /*[JsonProperty("items", NullValueHandling = NullValueHandling.Ignore)]
        public List<ItemOverview> Items { get; set; }*/


        public static AllItems_QuickType FromJson(string json)
        {
            return JsonConvert.DeserializeObject<AllItems_QuickType>(json, Warframe_Market_Manager.Lib.WFM.QuickType.AllItems_QuickType.Settings);
        }

        internal static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    public static class AllItems_QuickTypeExt
    {
        public static string ToJson(this AllItems_QuickType self)
        {
            return JsonConvert.SerializeObject(self, Warframe_Market_Manager.Lib.WFM.QuickType.AllItems_QuickType.Settings);
        }
    }

    public partial class Payload
    {
        [JsonProperty("items", NullValueHandling = NullValueHandling.Ignore)]
        public List<ItemOverview> Items { get; set; }
    }

    /*public partial class AllItems_ItemInfo
    {
        [JsonProperty("thumb", NullValueHandling = NullValueHandling.Ignore)]
        public string Thumb { get; set; }

        [JsonProperty("item_name", NullValueHandling = NullValueHandling.Ignore)]
        public string ItemName { get; set; }

        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public string Id { get; set; }

        [JsonProperty("url_name", NullValueHandling = NullValueHandling.Ignore)]
        public string UrlName { get; set; }
    }*/

    /*public partial class AllItems
    {
        public static AllItems FromJson(string json) => JsonConvert.DeserializeObject<AllItems>(json, Warframe_Market_Manager.Lib.WFM.QuickType.AllItemsConverter.Settings);
    }*/

    /*public static class AllItemsSerialize
    {
        public static string ToJson(this AllItems self) => JsonConvert.SerializeObject(self, Warframe_Market_Manager.Lib.WFM.QuickType.AllItemsConverter.Settings);
    }*/

    /*internal static class AllItemsConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }*/
}
