// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Warframe_Market_Manager.Lib.WFM;
//
//    var profileOrdersConfig = ProfileOrdersConfig.FromJson(jsonString);

namespace Warframe_Market_Manager.Lib.WFM
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ProfileOrdersConfig
    {
        [JsonProperty("payload")]
        public Payload Payload { get; set; }
    }

    public partial class Payload
    {
        [JsonProperty("sell_orders")]
        public Order[] SellOrders { get; set; }

        [JsonProperty("buy_orders")]
        public Order[] BuyOrders { get; set; }
    }

    public partial class Order
    {
        [JsonProperty("item")]
        public MarketItem MarketItem { get; set; }

    }

    public partial class MarketItem
    {
        [JsonProperty("en")]
        public De En { get; set; }

        [JsonProperty("tags")]
        public string[] Tags { get; set; }

        [JsonProperty("ko")]
        public De Ko { get; set; }

        [JsonProperty("fr")]
        public De Fr { get; set; }

        [JsonProperty("zh-hans")]
        public De ZhHans { get; set; }

        [JsonProperty("de")]
        public De De { get; set; }

        [JsonProperty("pt")]
        public De Pt { get; set; }

        [JsonProperty("es")]
        public De Es { get; set; }

        [JsonProperty("zh-hant")]
        public De ZhHant { get; set; }

        [JsonProperty("ru")]
        public De Ru { get; set; }

        [JsonProperty("sv")]
        public De Sv { get; set; }

        [JsonProperty("icon")]
        public string Icon { get; set; }

        [JsonProperty("sub_icon")]
        public string SubIcon { get; set; }

        [JsonProperty("pl")]
        public De Pl { get; set; }
    }

    public partial class De
    {
        [JsonProperty("item_name")]
        public string ItemName { get; set; }
    }

    public partial class ProfileOrdersConfig
    {
        public static ProfileOrdersConfig FromJson(string json) => JsonConvert.DeserializeObject<ProfileOrdersConfig>(json, Warframe_Market_Manager.Lib.WFM.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this ProfileOrdersConfig self) => JsonConvert.SerializeObject(self, Warframe_Market_Manager.Lib.WFM.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
