// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Warframe_Market_Manager.Lib.WFM;
//
//    var profileConfig = ProfileConfig.FromJson(jsonString);

namespace Warframe_Market_Manager.Lib.WFM
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Profile_Config
    {
        [JsonProperty("profile")]
        public Profile Profile { get; set; }
    }

    public partial class Profile
    {
        [JsonProperty("unread_messages")]
        public long UnreadMessages { get; set; }

        [JsonProperty("platform")]
        public string Platform { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("has_mail")]
        public bool HasMail { get; set; }

        [JsonProperty("reputation")]
        public long Reputation { get; set; }

        [JsonProperty("region")]
        public string Region { get; set; }

        [JsonProperty("role")]
        public string Role { get; set; }

        [JsonProperty("avatar")]
        public string Avatar { get; set; }

        [JsonProperty("ingame_name")]
        public string IngameName { get; set; }

        [JsonProperty("check_code")]
        public string CheckCode { get; set; }

        [JsonProperty("linked_accounts")]
        public LinkedAccounts LinkedAccounts { get; set; }

        [JsonProperty("written_reviews")]
        public long WrittenReviews { get; set; }

        [JsonProperty("banned")]
        public bool Banned { get; set; }

        [JsonProperty("verification")]
        public bool Verification { get; set; }

        [JsonProperty("anonymous")]
        public bool Anonymous { get; set; }
    }

    public partial class LinkedAccounts
    {
        [JsonProperty("steam_profile")]
        public bool SteamProfile { get; set; }

        [JsonProperty("patreon_profile")]
        public bool PatreonProfile { get; set; }

        [JsonProperty("xbox_profile")]
        public bool XboxProfile { get; set; }
    }

    public partial class Profile_Config
    {
        public static Profile_Config FromJson(string json) => JsonConvert.DeserializeObject<Profile_Config>(json, Warframe_Market_Manager.Lib.WFM.Profile_Converter.Settings);
    }

    public static class Profile_Serialize
    {
        public static string ToJson(this Profile_Config self) => JsonConvert.SerializeObject(self, Warframe_Market_Manager.Lib.WFM.Profile_Converter.Settings);
    }

    internal static class Profile_Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
